project:
  type: website

website:
  title: "Mala's Website"
  navbar:
    right:
      - text: "Home"
        href: home.html
      - text: "About"
        href: about.html
      - text: "Assignments"
        menu:
          - text: "Assignment 1"
            href: assignment1.html
